services:
  db_national_reg:
    image: public.ecr.aws/docker/library/postgres:15.3-alpine
    container_name: db_national_reg
    networks:
      - local
    environment:
      - POSTGRES_DB=national_reg
      - POSTGRES_USER=dev_db
      - POSTGRES_PASSWORD=dev_db
    ports:
      - 5435:5432

networks:
  local:
